intermine/web/main/src/org/intermine/web/logic/WebUtil.java
intermine/webapp/main/resources/webapp/WEB-INF/functions.tld
intermine/webapp/main/resources/webapp/otherMinesLink.jsp

This adds a WebUtil function to check if an object supports a particular
path, and uses that to make sure the otherMinesLink jsp does not raise
an exception.
Fixes #902

Fixes #902 (report page fails to render)

---

intermine/api/main/src/org/intermine/api/bag/BagQuery.java

Fix LOOKUPs with wildcards. I don't really know how this worked before.
Sergio -- can you test this works with:
* templates and queries
* LOOKUPs and with regular constraints
* wildcards and regular strings
* list upload works as expected

fix LOOKUPs with wildcards. Refs #978

---

bio/webapp/resources/webapp/model/js/friendly-mines.js

Because of the way this bit of code is designed, we aren't correctly setting the orthologue parameter. This parameter is needed when we send genes that need to be converted. However it's currently being set always which is causing problems.
All mines now have orthologues loaded so we can get away with removing this for now. maybe.

Fix orthologue links by breaking them.

---

intermine/webapp/main/resources/webapp/bagDetails.jsp

This should hopefully fix the "embiggening" issue where im-tables popup previews are expanding off the page. This issue seems to have returned.
I can't test this because my test model doesn't have fields that are too long to run off the page.
Julie, if you get a chance, can you try deploying this to HumanMine? It's a simple one line CSS change in bagDetails.jsp. If it breaks everything then reverting should be easy.

Should fix problem where table cell popup previews are too big.

---

intermine/web/main/src/org/intermine/webservice/server/WebService.java

This is a small pull request that allows the value for the Allowed-Origin header to be set to a constant.
In your `.intermine/MINE.properties` file, set the following property:
```properties
ws.response.origin = *
```
Then the allowed-origins=* header will be set for all WS requests. You can also use this to restrict access by origin.

Allow the allowed origin to be preconfigured.

---

intermine/webservice/client/samples/compile-run.sh

The locations of the various Java packages has changed considerably since this file was written. I went through the samples and updated CLASSPATH in this script so the current location of JARs is used.

updated compile-run.sh for current layout

---

bio/core/main/src/org/intermine/bio/dataconversion/EnsemblIdResolverFactory.java
bio/core/main/src/org/intermine/bio/dataconversion/EntrezGeneIdResolverFactory.java
bio/core/main/src/org/intermine/bio/dataconversion/HgncIdResolverFactory.java
bio/core/main/src/org/intermine/bio/dataconversion/HumanIdResolverFactory.java
bio/core/main/src/org/intermine/bio/dataconversion/MgiIdentifiersResolverFactory.java
bio/core/main/src/org/intermine/bio/dataconversion/RgdIdentifiersResolverFactory.java
bio/core/main/src/org/intermine/bio/dataconversion/WormBaseIdResolverFactory.java
bio/core/main/src/org/intermine/bio/dataconversion/ZfinIdentifiersResolverFactory.java

This is to alleviate an issue where the user may not do this (e.g. they just put 
```
resolver.file.rootpath=/micklem/data/idresolver
```
in their mine.properties but then id resolution fails because the code was simply appending the specific id resolver file (e.g. /micklem/data/idresolverentrez instead of /micklem/data/idresolver/entrez).  The user may not notice this since not finding the file just prints a warning to the log and does not halt the build.
I would have loved to have a badly configured path throw an exception to halt the build.  However, it struck me that a user may only have an ID resolver for some sources.  It may be correct for other sources to carry on if they cannot find a resolver because the file does not exist.  Whilst I see in the code there is a mechanism to …

Always add slash to id resolver path

---

bio/webapp/resources/webapp/model/minePathwaysDisplayer.jsp
flymine/webapp/resources/webapp/WEB-INF/webconfig-model.xml
intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties

Version 0.0.2 of the pathways displayer is live in the dev cdn, but before going to production we'll want to push to the prod CDN.

Pathways displayer

---

bio/webapp/resources/webapp/model/cytoscapeNetworkDisplayer.jsp
intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties
intermine/webapp/main/resources/webapp/report.jsp

Protein/Gene types needed to be exposed to tweak the query for the interaction viewer. 
Exposing the summaryfields variables and the type of object being shown will hopefully mean fewer java/jsp-side updates for front end scripts. They're available as a js global under `window.imSummaryFields`
Note that before putting this change live on the prod server, we will need the CDN dev branch to be merged into master to ensure that version 1.0.1 of the interaction displayer is available from the intermine CDN.

Fix Protein cytoscape viewer and expose useful js variables on report page

---

intermine/integrate/main/src/org/intermine/dataloader/XmlDataLoaderTask.java

This saves loads of grief if the files are also open with an editor such as vim that creates backup files

Have XmlDataLoaderTask only pick up files ending with .xml.

---

bio/sources/go-annotation/main/src/org/intermine/bio/dataconversion/GoConverter.java
bio/sources/go-annotation/test/resources/GoConverterOboTest_tgt.xml

add withText to the key. Different GO annotations are created if there is a withtext value, so we need to create an annotation for each. Refs #1293 
To test:
1. duplicate GO annotations are created if they both have with text (example given in ticket
2. GO annotations with multiple entries are not duplicated if they do not have with text.
Tell @kkarra and @rachellyne

GO - discarding evidence if annotation has a value for "with text"

---

bio/sources/uniprot/main/src/org/intermine/bio/dataconversion/UniprotConverter.java
bio/sources/uniprot/main/src/org/intermine/bio/dataconversion/UniprotEntry.java

Fixes two issues with handling of isoform synonyms in the Uniprot source converter.
1. Additional isoform names were not being picked up as synonyms.
2. The id of the specific isoform chosen as the canonical was being propagated to all other isoforms.
I will warn you in advance that some of this code is pretty contorted. In my own defense, the flow of handling isoforms was already pretty subtle.

Fix handling of isoform synonyms. 

---

biotestmine/setup.sh

The default sed on OSX doesn't like using -i with no arguments. Replacing this with -i '' allows biotestmine to be built
The error you get otherwise is
```
#---> Checking databases...
#--- biotestmine-userprofile exists.
#--- biotestmine exists.
#--- biotestmine-items exists.
#--- Sample data already exists.
#---> Personalising project.xml
sed: 1: "project.xml": extra characters at the end of p command
```

Fix sed bsd

---

biotestmine/setup.sh

This is a follow up to the previous correction with sed for the biotestmine https://github.com/intermine/intermine/pull/1389
I used a syntax in #1389 that turned out to not be compatible with linux sed after fixing it for mac. Going back, i saw that testmodel/setup.sh simply used this syntax, and it seems to be a simpler option that works well in both OSs (it is not fully in place editing but not really necessary I think).

Fix BSD sed vol 2 for biotestmine

---

biotestmine/dbmodel/resources/genomic_priorities.properties

This is a follow up to the discussion from https://groups.google.com/forum/#!category-topic/intermine/database-build/oSzjmkgvzOI
In that thread we saw an error in ./biotestmine/setup.sh which came from ant -v -Dsource=uniprot-malaria
```
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.intermine.dataloader.IntegrationWriterFactory.getIntegrationWriter(IntegrationWriterFactory.java:65)
... 32 more
Caused by: java.lang.IllegalArgumentException: Problem instantiating …
```

Remove ProteinDomain.shortName from biotestmine genomic_properties

---

intermine/perl/Webservice-InterMine/lib/Webservice/InterMine/ResultIterator.pm
intermine/perl/Webservice-InterMine/lib/Webservice/InterMine/Types.pm

Hi,
I added the NetHTTPS type after Joe had some issues using HTTPS for the web service.
I am not very familiar with this code base, so please do review these changes carefully.  I ran a single test to double check that my changes didn't break anything obvious.
prove -I lib -I../InterMine-Model/lib/ t/06_service/02_result_iterator.t
t/06_service/02_result_iterator.t .. ok
All tests successful.
Files=1, Tests=4,  1 wallclock secs ( 0.02 usr  0.00 sys +  0.39 cusr  0.01 csys =  0.42 CPU)
Result: PASS
Cheers,
Josh

Added NetHTTPS type

---

intermine/api/main/src/org/intermine/api/bag/BagManager.java

Refs #1404
Global lists should always be CURRENT.
Lists per user can be whatever status.
Example:
LIST A should not be included in global lists because it is not current. It would be returned if Rachel logged in and asked for her lists however.

only return CURRENT public lists

---

intermine/api/main/src/org/intermine/api/profile/Profile.java
intermine/api/main/src/org/intermine/api/profile/ProfileManager.java

Delete all queries, then save templates from memory.
Inefficient but low traffic. Should refactor as part of #225

Delete templates correctly

---

intermine/webapp/main/resources/webapp/errorMessages.jsp

Escapes the template name to address https://github.com/intermine/intermine/issues/1396. Thanks @scarabmonkey for reporting the issue. 
Could realistically be addressed here https://github.com/intermine/intermine/blob/d48d60f446753de8b591611787d0ed0d156606c1/intermine/web/main/src/org/intermine/web/struts/TemplateController.java#L88-L89 instead / as well, but we use the `>` character in template names so it's not quite as simple as excluding `>` and `<`s.

escape template name  in error messages

---

bio/webapp/resources/webapp/model/genomic_region_search/genomic_region_search_results_default.js

I've seen that the region search result page ends up triggering the pop-up blocker in many browsers including both the latest chrome and firefox.
There are probably workarounds to make and the pop-up open legitimately, but I figured the easiest thing to do is to actually just open the results in the current tab after hitting the "Go" button, since hitting the back button seems to be fine anyways.
Hopefully by not triggering the popup blocker it would not confuse any users of the service, especially when pop-up blocked results can go unnoticed

Add fix for popup blocker being triggered on region search results

---

intermine/web/main/src/org/intermine/web/logic/widget/GraphWidget.java
intermine/web/main/src/org/intermine/web/logic/widget/GraphWidgetLoader.java
intermine/web/main/src/org/intermine/web/logic/widget/WidgetLdr.java
intermine/web/test/resources/WebConfigTest.xml
intermine/web/test/src/org/intermine/web/logic/widget/GraphWidgetTest.java
intermine/web/test/src/org/intermine/web/logic/widget/WidgetConfigTestCase.java

Fixed the bug in the graph widget. Now the user can set e.g. in the flyatlas_for_gene widget, the attribute constraint as  "presentCall != 0, presentCall != 1, presentCall != 2". The valid operators are still "=" and "!="

Widget constraints

---

bio/webapp/src/org/intermine/bio/web/logic/GenomicRegionSearchUtil.java

Support strand-specific queries

---

bio/webapp/src/org/intermine/bio/web/model/GenomicRegionSearchConstraint.java

Add strandSpecific boolean to constructor and equals() method

---

bio/webapp/src/org/intermine/bio/webservice/GenomicRegionSearchListInput.java

Add support for strandSpecific boolean

---

bio/webapp/src/org/intermine/bio/webservice/GenomicRegionSearchService.java

Add support for strand-specific search

---

intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties

Older Google accounts use the `openid` scope to resolve the _name_ field which is stored in the UserPreferences table as _alias_. Under this scope, newer Google accounts have empty string values in these fields hence the error:
`Error granting permission: No two users may have the same value for 'alias', but the value '' is already taken`
By adding the `profile` scope we expose the _name_ field in the oAuth2 response for newer accounts.
A side effect of adding this scope is that Google users will be prompted to re-grant permission to access their basic profile information.

Include google profile scope in oauth2 workflow

---

bio/core/main/src/org/intermine/bio/dataconversion/OboConverter.java

Allow for multiple xrefs Refs #1545
I keep the xrefs in a map and store at the end of the process. This ensures the xrefs have references to ALL ontology terms, not just the first one!
@JoelRichardson Can you test this?

allow for multiple xrefs Refs #1545

---

bio/core/main/src/org/intermine/bio/dataconversion/OboConverter.java

Some OBO files have terms which are missing the name attribute. The code assumed that it exists, and the import therefore threw a fatal RunException when it hit a term which had a blank name attribute. This update simply tests for existence first, just as it already did for identifier (which, I thought, actually IS required in an OBO!).

Allow the name attribute to be missing

---

intermine/objectstore/main/src/org/intermine/sql/Database.java

see #966 .
you need to add a line to db properties settings like:
`db.your_source.datasource.schema=your_schema`
for example
`db.tripaldbname.datasource.schema=chado`
i'll add a note here
http://intermine.readthedocs.io/en/latest/database/data-sources/library/chado/?highlight=tripal
if fine.
Note: removed classloader (very long string) info from the log about opening/closing of db connections.

adds handling of schema property (e.g. tripal), simplifies logs

---

bio/core/main/src/org/intermine/bio/dataconversion/GFF3Converter.java
bio/skeletons/source/main/resources/${source-name}_config.properties
bio/skeletons/source/main/resources/.gitignore
intermine/model/main/src/org/intermine/metadata/StringUtil.java

The GFF3 data source (in bio-core) has a config file in bio/core/resources, gff_config.properties.
This now can be overridden by source-specific config files. e.g. bio/sources/fly/long-oligo/main/resources/long-oligo_config.properties. The source looks for the source specific file first, then uses the default if it's not there. This is consistent with the keys file as well.
1. Make sure properties are correct when (a) there is a source specific file (b) there is not a source specific file and the default GFF3 file is used.
2. Sources without a config file are run correctly.
There is no case where the gff_config.properties file is not there.

allow each GFF source to specify their own config file. Refs #1325

---

intermine/api/main/src/org/intermine/api/query/MainHelper.java

if user enters * into LOOKUP constraint, drop that constraint. They want EVERYTHING. Refs #1471
Test carefully!
* List upload
* Any template or query with a LOOKUP constraint
I didn't touch the bagqueryrunner code (the bit that does the LOOKUP part). That still treats `*` as a string. This is correct behaviour. If someone enters a `*` on the list upload it will be treated like a string. We don't want to make a list of everything!
All I did here was to drop the LOOKUP constraint if it equals `*` in its entirety. This means the constraint won't be there so the query will return all results, which is what the user wanted.
Check my logic!

Handle wildcards in LOOKUP constraints correctly.

---

intermine/web/main/src/org/intermine/web/logic/Constants.java
intermine/web/main/src/org/intermine/web/logic/widget/EnrichmentCalculation.java
intermine/web/main/src/org/intermine/web/logic/widget/EnrichmentResults.java
intermine/web/main/src/org/intermine/web/logic/widget/EnrichmentWidget.java
intermine/web/main/src/org/intermine/web/logic/widget/Widget.java
intermine/web/main/src/org/intermine/webservice/server/widget/EnrichmentJSONProcessor.java
intermine/web/main/src/org/intermine/webservice/server/widget/EnrichmentWidgetResultService.java
intermine/web/main/src/org/intermine/webservice/server/widget/EnrichmentXMLProcessor.java

There are four numbers used to calculate enrichment:
```
n
the number of objects in your list
N
the number of objects in the reference population, e.g. number of genes anntotated 
with ANY GO term 
k
the number of objects annotated with this item in your list
M
the number of objects annotated with item in the reference population 
```
See http://intermine.readthedocs.io/en/latest/embedding/list-widgets/enrichment-widgets/
These numbers are now in the enrichment output:
<table>
<tr>
<td>n
</td>
<td> the number of objects in your list
</td>
<td>the list size
</td>
</tr>
<tr>
<td>N
</td>
<td> the number of objects in the reference population
</td>
<td>`populationCount` attribute in the header
</td>
</tr>
<tr>
<td>k
</td>
<td>the number of objects annotated with this item in your list
</td> …

Add the 4 numbers used to calculation the enrichment value

---

intermine/objectstore/main/src/org/intermine/sql/writebatch/BatchWriterPostgresCopyImpl.java

Minor issue: I had a mine with a table named gene in a different schema. When counting rows, the query did not restrict to the public schema and I got a build exception.

only look in public schema when counting rows in a table

---

intermine/web/main/src/org/intermine/web/struts/oauth2/Callback.java

Simple fix to the OAuth2 Callback controller to enable tracking of user logins in the LOGIN_TRACK_TABLE (`logintrack` table in the userprofile DB).
Thanks to @JoeCarlson for his pointers regarding this issue (on the IM Discord chat)!

Enables user login tracking in LOGIN_TRACK_TABLE for OAuth2 flow

---

intermine/web/main/src/org/intermine/web/util/URLGenerator.java

The port handling of generateURL and getCurrentURL broke the permaLink on HTTPS sites. This fixes that problem. Tested on live BeanMine.

Update URLGenerator.java to handle HTTPS sites

---

bio/sources/uniprot/main/src/org/intermine/bio/dataconversion/UniprotConverter.java
bio/sources/uniprot/main/src/org/intermine/bio/dataconversion/UniprotEntry.java
bio/sources/uniprot/test/resources/7227_testing_sprot.xml
bio/sources/uniprot/test/resources/UniprotConverterTest_tgt.xml
intermine/pathquery/main/src/org/intermine/pathquery/PathQueryHandler.java
intermine/webapp/main/resources/webapp/WEB-INF/web.xml

I removed node from the XML parsing. I looked in the main query, and it's not parsed there at all (that I could see).
"node" isn't generated as an XML element anymore, nor is it used in JSON. We included this in the list of things that were being phased out as well.

Remove "node" element from pathquery XML parsing

---

bio/sources/update-publications/main/src/org/intermine/bio/dataconversion/EntrezPublicationsRetriever.java

*Fix an issue with the getReader() function in EntrezPublicationsRetriever.java file. update-publications always fail, if too much pubmed ids are send to Entrez server. This is because getReader() uses HTTP GET method to send the request. The message size or url length is limited when HTTP GET method is used. Change function to use HTTP POST method instead of HTTP GET method which is not limited by length.*

Add publication-fix

---

bio/sources/build.gradle
plugin/src/main/groovy/org/intermine/plugin/dbmodel/DBModelPlugin.groovy
plugin/src/main/groovy/org/intermine/plugin/dbmodel/DBModelUtils.groovy
plugin/src/main/groovy/org/intermine/plugin/integrate/IntegratePlugin.groovy
plugin/src/main/groovy/org/intermine/plugin/postprocess/PostProcessPlugin.groovy
plugin/src/main/java/org/intermine/plugin/project/PostProcess.java
plugin/src/main/java/org/intermine/plugin/project/ProjectXmlBinding.java

Users need to be able to version their sources. I did this in #1899. However I missed two things:
* Postprocesses need to be versioned in the same way
* Generating the keys file to use also puts bio-sources on the classpath and needs to use the custom version. I don't know how I missed that in the original commit? 
* Versioning sources works with and without a version specified in project XML file
* Versioning postprocesses works with and without a version specified in project XML file
I don't know how I missed the keys thing, so please be sure to clean. However, I am pretty sure I _did_ do a clean. The code worked on FlyMine and locally but NOT in HumanMine. Don't know why. 
(I haven't done documentation yet)

Versioned postprocesses

---

bio/core/src/main/java/org/intermine/bio/io/gff3/GFF3Parser.java
bio/core/src/main/java/org/intermine/bio/io/gff3/GFF3Record.java

The header of the GFF file (the top bit that has a #) often has important metadata, such as the genome build, date of annotation, etc. but is discarded.
Instead, I set the header to a variable, and made that variable available in the `GFFRecord`
See: #1786
@sergiocontrino Can you test that the GFF loading still works as expected? I only changed the constructor.
@JoelRichardson Can you verify this is what you asked for?

GFF: add header

---

intermine/api/src/main/java/org/intermine/api/query/codegen/WebserviceJavaCodeGenerator.java
intermine/webapp/src/main/webapp/apiJava.jsp

There was a small bug in the Java client but I couldn't fix because the compile scripts rely on having the old local JARs.
I've updated the Java client to use the new gradle build system.
* [client](https://github.com/intermine/intermine-ws-java)
* [examples](https://github.com/intermine/intermine-ws-java-docs)
* [javadoc](http://intermine.org/intermine-ws-java/javadoc/)
* [user docs](https://intermine.readthedocs.io/en/latest/web-services/#api-and-client-libraries)
* Docs are complete
* Autogenerate is correct
* Examples work. 
* Travis passes

Update Java client to use Gradle

---

bio/sources/panther/src/main/java/org/intermine/bio/dataconversion/PantherConverter.java

This is another pull request regarding ThaleMine 4.1.0 upgrade. This pull request converts Arabidopsis (Taxon 3702) gene IDs to uppercase for Panther data loader. If IDs are not converted to uppercase, Intermine ends up creating two gene ID records with two gene report pages. For example, one record is created for At5g04395 and another for AT5G04395.
Please see our working version of Panther data source override here:
[https://github.com/asherpasha/thalemine-bio-sources](https://github.com/asherpasha/thalemine-bio-sources)
Travis testing.

BAR ThaleMine - 3

---

intermine/objectstore/src/main/java/org/intermine/task/GenerateUpdateTriggersTask.java

You learn something new everyday. The SQL standard for casting a float to an integer rounds to the nearest integer; it does not truncate. When calculating the value for the serial after (possibly) adding new IntermineObjects into the database with remove_update_triggers.sql, I needed to add an explicit floor() function call.
When the maximum id of IntermineObject divided by 1,000,000 rounds up to an integer, the value of serial should be the floor of the maximum id divided by 1,000,000.

correct the cast conversion when updating serial

---

bio/core/src/main/java/org/intermine/bio/dataconversion/GFF3RecordHandler.java

It doesn't make sense to remove the feature without removing its associated Location -- which causes a build error because the Location gets orphaned in the Items database.

Add clearLocation() to removeFeature()

---

bio/sources/entrez-organism/src/main/java/org/intermine/bio/dataconversion/EntrezOrganismRetriever.java

I am working on Candidamine for candida species, and some organism that are loaded in the mine start with **[** e.g **[Candida] auris** or **[Candida] glabrata**. This lead to a strange  short name for example **[.auris**.
This fix such behaviour.

Fix organism short name formation.

---

bio/model/core.xml

BioEntity extends Annotatable so it already has ontologyAnnotations. Removing from the BioEntity definition to avoid confusion. (And because I'm picky.)

Remove BioEntity.ontologyAnnotations (redundant)

---

intermine/webapp/src/main/webapp/report.jsp

This pull request fixes the following bug in the reports page:
If 'field.doNotTruncate' is set to true, then the label is not displayed correctly. Instead 'field.name' is shown.
We have tested the changes in the development version of ThaleMine.

BAR ThaleMine - 6: Fixed a minor bug in reports page long fields

---

testmine/build.gradle
testmine/gradle/wrapper/gradle-wrapper.properties

This pull request updates testmine Gradle to 4.9. This is required for InterMine Client upgrade to Python 3.8. Please test and merge, so we can test the client on Travis.
Related issue #2271 
Travis testing

Updated testmine to Gradle 4.9

---

intermine/webapp/src/main/webapp/convertBag.jsp

Fixes #2282.
Google Charts recently deprecated https://www.google.com/jsapi and replaced it with https://www.gstatic.com/charts/loader.js via a 301 redirect. The new charts loader is actually backwards compatible, (I have tested this fix with both list-widgets 2.1.4 and 2.1.5, which are before and after adopting the [new API](https://developers.google.com/chart/interactive/docs/basic_load_libs#update-library-loader-code)) but a nefarious piece of near decade old code breaks a JS language feature which the new charts loader happens to rely on.
I only moved the `hasOwnProperty` function definition to be inline where it's used, but since it used to globally override the built-in, it *could* break other JS code which relies on this incorrect implementation of `hasOwnProperty` further down in …

Do not override hasOwnProperty JS builtin, fixing list-widgets

---

testmine/setup.sh
testmine/webapp/build.gradle

removed gretty from testmine because the task tomcatStartWar doesn't work with gradle 4.9.
gretty has been replaced with the plugin cargo.
instead of using tomcatStartWar task, we use cargoRunLocal.
travis is ok, and I was able to run testmine locally using cargoRunLocal

Removed gretty plugin from testmine

---

intermine/api/src/main/java/org/intermine/api/results/ResultElement.java
intermine/webapp/src/main/java/org/intermine/webservice/server/output/JSONResultsIterator.java
intermine/webapp/src/main/java/org/intermine/webservice/server/query/result/PathQueryBuilderForJSONObj.java

This fixes https://github.com/intermine/intermine/issues/2302 . Instead of having a null value for the id of a simple object which is the root of a PathQuery, which breaks a format=jsonobjects query, a "fake" id is created by ResultElement.setSimpleCellId() for the given cell, and this method is called in JSONResultsIterator if necessary. It is only called there, and only if the root class lacks an id, so "normal" queries are unchanged. The id is dropped from the rebuilt query in PathQueryBuilderForJSONObj and the original order-by is restored.
I have tested this against a query on my ExpressionValue, which is a simple object, as well as against "normal" queries on root classes such as Gene or SequenceFeature. I've attached an HTML which demonstrates that the jsonobjects format works. …

Fix format=jsonobjects queries for simple root classes

---

bio/webapp/src/main/webapp/model/geneExpressionAtlasDiseasesDisplayer.jsp
bio/webapp/src/main/webapp/model/geneExpressionAtlasTissuesDisplayer.jsp

A fix for the broken humanmine expression viewers on the gene report page mentioned here: #2282
#2283 only fixed the flymine list widgets; this PR fixes the separate problem causing the humanmine displayers to fail.
It's really only backgroundColor that causes the error, but hAxis and legend are also invalid and don't seem to have an effect (according to https://developers.google.com/chart/interactive/docs/gallery/barchart).
I didn't look into reimplementing the background color with its correct property as the displayer seems to look fine as it is.
I only tested this fix with each displayer isolated. You'll need to update the jsp files in a humanmine to test properly.

Remove invalid draw options, fixing geneExpressionAtlas displayers

---

bio/core/src/main/java/org/intermine/bio/dataconversion/GFF3Converter.java
bio/core/src/test/java/org/intermine/bio/dataconversion/GFF3ConverterTest.java
bio/core/src/test/resources/GFF3ConverterTest.xml
bio/core/src/test/resources/GFF3ConverterTestDiscontinuous.xml
bio/core/src/test/resources/GFF3ConverterTestRGD.xml
bio/core/src/test/resources/GFF3ConverterTestUnLocated.xml

Removed setAttribute("scoreType", record.getSource()) since it's fundamentally wrong. The score type is not given in a GFF3. The source is not the score type.

Remove setting scoreType in GFF3Converter.java

---

bio/sources/build.gradle
intermine/build.gradle
testmine/build.gradle

This pull request fixes CVE-2021-44832 (also RCE bug). Log4j 2.17.0 is upgraded to 2.17.1. I am not sure if InterMine is exploitable using these Log4j bugs, but we should fix this for compliance, department security policy etc. 
Works on GitHub actions

Log4j fix round 3
