intermine/intermine

RELEASE_NOTES
intermine/api/main/src/org/intermine/api/mines/LocalMine.java

To test release a mine without defaultValues set, e.g delete this if you are releasing a test flymine: https://github.com/intermine/intermine/blob/beta/intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties#L187-L193
This should be a selenium test.
This is high priority because the list upload will fail for un-friendly mines.
Fixes #922

List upload: exception thrown when it can't find default organism

---

intermine/webapp/main/resources/webapp/bagUploadConfirm.jsp

Fixes #932 
Default list names now follow this pattern:
*[Data Type]* list for *[Organism] [Date]*
Example: Protein list for D. melanogaster 3 Feb 2015 16.11
If "ANY" organism is selected:
*[Data Type]* list for all organisms *[Date]*
Example: Protein list for all organisms 3 Feb 2015 16.12

Default list names now include the data type and the organism.

---

bio/sources/panther/main/src/org/intermine/bio/dataconversion/PantherConverter.java

don't store duplicate homologues. Refs #957

---

intermine/web/main/src/org/intermine/dwr/AjaxServices.java

Please enter the commit message for your changes. Lines starting

fixes 958 (error message improvement)

---

bio/sources/treefam/main/resources/treefam_config.properties
bio/sources/treefam/main/src/org/intermine/bio/dataconversion/TreefamConverter.java

don't store duplicate homologues. Refs #957 and #960

remove duplicates from treefam too

---

intermine/webapp/main/resources/webapp/js/list-listener.js
intermine/webapp/main/resources/webapp/js/notifications.js
intermine/webapp/main/resources/webapp/resultsTable.jsp

InterMine 1.5.1 - results tables updates

---

intermine/api/main/src/org/intermine/api/query/codegen/WebserviceJavaCodeGenerator.java
intermine/pathquery/main/src/org/intermine/pathquery/Constraints.java

Fixes #967. Replaces #1008 as it needed a tests fixing.

Java client fix 

---

intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties
intermine/webapp/main/resources/webapp/widgetScript.jsp

This fixes the View button on list-widgets. It removes the Save button until we can rewire it back to im-tables 2.0.
Resolves issue #1021

Fixes "View" button on list (enrichment) widgets.

---

intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties
intermine/webapp/main/resources/webapp/widgetScript.jsp

Fixes list-widget's "view results" button.

---

intermine/integrate/main/src/org/intermine/task/TSVFileReaderTask.java

Close DirectDataloader so objects are stored.

---

intermine/api/main/src/org/intermine/api/bag/BagManager.java
intermine/web/main/src/org/intermine/web/logic/query/DisplayConstraint.java

Hi @julie-sullivan 
Hope I'm doing this right!

Allow supertype lists in bag constraints.

---

bio/sources/vcf/.checkstyle
bio/sources/vcf/.classpath
bio/sources/vcf/.project
bio/sources/vcf/build.xml
bio/sources/vcf/ensembl-snp_additions.xml
bio/sources/vcf/main/build.xml
bio/sources/vcf/main/project.properties
bio/sources/vcf/main/resources/.gitignore
bio/sources/vcf/main/src/org/intermine/bio/dataconversion/VcfLoaderTask.java
bio/sources/vcf/project.properties
bio/sources/vcf/resources/vcf_keys.properties
bio/sources/vcf/test/build.xml
bio/sources/vcf/test/project.properties
bio/sources/vcf/test/resources/Homo_sapiens.vcf
bio/sources/vcf/test/resources/ensembl-snp-expected.xml
bio/sources/vcf/test/resources/vcf-test_keys.properties
bio/sources/vcf/test/src/org/intermine/bio/dataconversion/VcfLoaderTaskTest.java
bio/sources/vcf/vcf_additions.xml

A parser for VCF files. Tested using Ensembl. ftp://ftp.ensembl.org/pub/release-79/variation/vcf/homo_sapiens/

Parser for VCF data files

---

intermine/webapp/main/resources/webapp/reportTemplate.jsp

`cherry-pick` failed for 12bd648da9ad6a4724255adecfac9e90867593dc

merge #1075 into master

---

intermine/objectstore/main/src/org/intermine/objectstore/intermine/ResultsConverter.java

Fix results error where start of an outer join is a simple object.

---

intermine/scripts/log_analysis/analyse_log.py
intermine/scripts/log_analysis/dataloaded_graph.py

Two python scripts to analyse intermine.log files from a build:
1) extract and print time taken running SQL ANALYSE during a build
2) extract dataloading speed in objs/min for each source and render a chart

Log analysis python scripts

---

bio/sources/panther/main/src/org/intermine/bio/dataconversion/PantherConverter.java

process homologues properly

---

intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties

This bumps IMJS to version 3.14.1 which includes bug fixes.

Include latest IMJS (3.14.1) bug fixes.

---

intermine/web/main/src/org/intermine/web/logic/results/InlineList.java

Prevent null objects from being added to the linline list collection.

Report page: Null pointer exception when inline lists are configured but there's no data

---

intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties

~~NOTE: this pull is dependent on the current dev branch of the CDN being merged into master. Until it is, this pull will NOT work, because the file it's pointing to won't be there.~~
Ignore that, as beta flymine points to the dev CDN.

pointed filesaver.js to a more recent version so that we could handle #1166

---

bio/sources/panther/main/src/org/intermine/bio/dataconversion/PantherConverter.java
humanmine/project.xml

Refs #1209 but should have been fixed by #1081

fix flaw in logic. Refs #1209

---

bio/sources/protein2ipr/protein2ipr_additions.xml

numbers should be ints not strings! 

---

bio/tutorial/project.xml

remove interpro parameter, it's not valid anymore. Refs #1228

Fix tutorial

---

intermine/api/main/src/org/intermine/api/template/ApiTemplate.java
intermine/api/main/src/org/intermine/api/template/TemplateHelper.java
intermine/api/main/src/org/intermine/api/template/TemplateManager.java
intermine/pathquery/main/src/org/intermine/template/TemplateQuery.java
intermine/web/main/src/org/intermine/webservice/server/template/AvailableTemplatesService.java

Refs #1154 
Add template tags to toJSON() method on templates.

Add template tags to JSON export.

---

bio/sources/psi-complexes/main/src/org/intermine/bio/dataconversion/PsiComplexesConverter.java

on finding a new type, set as bioentity instead of throwing an excepton. Refs #1168

Complex interactions: on new type create generic item instead of throwing exception.

---

flymine/project.xml
intermine/web/main/src/org/intermine/web/struts/InterMineRequestProcessor.java

Refs #1184 
Don't require a session for the keyword search results.

Keyword session

---

intermine/web/main/src/org/intermine/web/struts/KeywordSearchResultsController.java

don't show all search index if there is no keyword. Refs #1236

Keyword Search: don't show all search index if there is no keyword.

---

intermine/web/main/src/org/intermine/web/struts/ModifyTemplateAction.java
intermine/web/main/src/org/intermine/web/struts/TemplatesExportAction.java
intermine/web/main/src/org/intermine/web/struts/WebserviceCodeGenAction.java

fix template export. Refs #1221

Templates: fix export

---

bio/sources/kegg-pathway/main/src/org/intermine/bio/dataconversion/KeggPathwayConverter.java
bio/sources/kegg-pathway/test/resources/KeggConverterTest_tgt.xml
bio/sources/kegg-pathway/test/src/org/intermine/bio/dataconversion/KeggPathwayConverterTest.java

Minor change.
* Add human gene to unit test
* remove obsolete variable
* make error message not flymine-specific.

KEGG - add human gene to unit test

---

bio/sources/uniprot/main/src/org/intermine/bio/dataconversion/UniprotConverter.java
bio/sources/uniprot/test/resources/7227_testing_sprot.xml
bio/sources/uniprot/test/resources/UniprotConverterTest_tgt.xml
bio/sources/uniprot/test/src/org/intermine/bio/dataconversion/UniprotConverterTest.java

add description of disease to comment. Refs #1202

UniProt comments - add disease

---

intermine/webapp/main/resources/webapp/reportTemplate.jsp

Do not use intermine.utils.numToString()

Reimplement fix for missing template counts.

---

flymine/default.intermine.webapp.properties
intermine/web/main/src/org/intermine/webservice/server/lists/ListTagService.java

if the user is not logged in, return empty set instead of lists. Refs #1222

Fix /list/tags web service

---

intermine/web/main/src/org/intermine/webservice/server/template/TemplateToListService.java

Web service - Template to list fix

---

bio/sources/uniprot/main/src/org/intermine/bio/dataconversion/UniprotConverter.java

Hi Julie,
Hope I did this right...
Joel

Added 'creategenes' option for Uniprot source.

---

intermine/web/main/src/org/intermine/web/logic/config/FieldConfig.java
intermine/web/main/src/org/intermine/web/logic/results/ReportObject.java
intermine/webapp/main/resources/webapp/WEB-INF/webconfig-model.xsd

Added a "hide" field config option. Allows developer to prevent a field from displaying on a report page.

Allow fields to be hidden on report pages.

---

intermine/web/main/src/org/intermine/webservice/server/template/result/TemplateResultLinkGenerator.java

Remove obsolete restriction. Generate web service links even if there is a list constraint.

---

intermine/web/main/src/org/intermine/web/logic/Constants.java
intermine/webapp/main/resources/webapp/WEB-INF/web.xml

Add a web service for intermine version.
> /service/version/intermine
Produces this:
```
InterMine Version
"1.6.5"
```
> /service/version/webservice
```
API Version
19
```
But only because of wildcard.

add web service for intermine version

---

intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties

Fix for https://github.com/intermine/intermine/issues/1225. The new script version is live in the CDN already.

Cytoscape nicer errors

---

intermine/web/main/src/org/intermine/web/logic/Constants.java
intermine/web/main/src/org/intermine/webservice/server/VersionService.java
intermine/webapp/main/resources/webapp/WEB-INF/web.xml

Add a web service for intermine version.
/service/version/intermine
Produces this:
InterMine Version
"1.6.5"
/service/version/webservice
API Version
19

add intermine version option to release web service

---

intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties

Issue: https://github.com/intermine/intermine/issues/1274 fix tested ok by kalpana

Point global.web.properties file to the fix for NULL pubmed ID

---

flymine/webapp/resources/web.properties
intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties
intermine/webapp/main/resources/webapp/footer.jsp

Refs #1276
The footer looks wonky now. @yochannah Can you help?
* Add Android app icon? Or too crowded already?
* Maybe add a warning too:
```
Users of the database are solely responsible for compliance
with any copyright restrictions, including those applying to the author
abstracts. Documents from this server are provided "AS-IS" without any
warranty, expressed or implied.
```

add citation bit to footer, need docs

---

intermine/api/main/src/org/intermine/api/tracker/track/TrackAbstract.java
intermine/api/test/src/org/intermine/api/profile/XMLReadTest.java
intermine/api/test/src/org/intermine/api/tracker/TrackerDelegateTest.java
intermine/integrate/main/src/org/intermine/dataloader/BaseEquivalentObjectFetcher.java
intermine/integrate/main/src/org/intermine/dataloader/BatchingFetcher.java
intermine/integrate/main/src/org/intermine/dataloader/EquivalentObjectFetcher.java
intermine/integrate/main/src/org/intermine/dataloader/HintingFetcher.java
intermine/integrate/main/src/org/intermine/dataloader/IntegrationWriterAbstractImpl.java
intermine/integrate/main/src/org/intermine/dataloader/IntegrationWriterDataTrackingImpl.java
intermine/integrate/test/src/org/intermine/dataloader/IntegrationWriterDataTrackingImplTest.java
intermine/objectstore/main/src/org/intermine/objectstore/proxy/LazyCollection.java
intermine/objectstore/main/src/org/intermine/objectstore/query/SingletonResults.java
intermine/webtasks/main/src/org/intermine/web/task/EvictOrphansTask.java

Reverts intermine/intermine#1356

Revert "Java 8"

---

intermine/web/main/src/org/intermine/web/util/URLGenerator.java
intermine/webapp/main/resources/webapp/layout.jsp

to be tested. needs update of properties files.

to allow https protocol

---

bio/webapp/src/org/intermine/bio/web/widget/GeneLengthCorrectionCoefficient.java
intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties

Should have been part of #1258 and #1290. whoops.
Only FlyMine uses the gene length correction, so when I updated the enrichment widgets I accidentally left that part out. See the `correctionCoefficient` in FlyMine's config file:
```
<enrichmentwidgetdisplayer id="go_enrichment_for_gene"
title="Gene Ontology Enrichment"
description="GO terms enriched for items in this list."
label="GO Term"
filterLabel="Ontology"
filters="biological_process,cellular_component,molecular_function"
startClass="Gene"
startClassDisplay="primaryIdentifier"
enrich="goAnnotation.ontologyTerm.parents.name"
enrichIdentifier="goAnnotation.ontologyTerm.parents.identifier"
constraints="goAnnotation.ontologyTerm.parents.namespace=[Ontology],organism.name=[list],
primaryIdentifier != null, goAnnotation.qualifier = null, …
```

Missing part of #1258

---

testmodel/testmodel.properties

If you're Travis and you're happy clap your hands. Fixes issue #1398 
Python and JavaScript tests pass again. We're green across the board.
@julie-sullivan Can you test Intermine in Docker to make sure it still works as expected?

Include port in the testmodel's baseurl property

---

intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties

don't set default, leave blank. Refs #1402

Refactor mail (fix)

---

bio/webapp/resources/webapp/model/genomicRegionSearchOptionsBase.jsp

modified:   bio/webapp/resources/webapp/model/genomicRegionSearchOptionsBase.jsp
modified:   bio/webapp/src/org/intermine/bio/web/logic/GenomicRegionSearchService.java
modified:   bio/webapp/src/org/intermine/bio/web/logic/GenomicRegionSearchUtil.java
modified:   bio/webapp/src/org/intermine/bio/web/model/GenomicRegion.java
modified:   bio/webapp/src/org/intermine/bio/web/model/GenomicRegionSearchConstraint.java
modified:   bio/webapp/src/org/intermine/bio/web/struts/GenomicRegionSearchAction.java
modified:   bio/webapp/src/org/intermine/bio/webservice/GenomicRegionSearchListInput.java
modified:   bio/webapp/src/org/intermine/bio/webservice/GenomicRegionSearchService.java

Add strandSpecific checkbox

---

bio/webapp/src/org/intermine/bio/web/logic/GenomicRegionSearchService.java

Add support for new field GenomicRegion.minusStrand

---

bio/webapp/src/org/intermine/bio/web/model/GenomicRegion.java

Added minusStrand field and get/setters

---

bio/webapp/src/org/intermine/bio/web/struts/GenomicRegionSearchAction.java

Add support for new minusStrand boolean

---

intermine/web/main/src/org/intermine/web/struts/ModifyBagAction.java

fixed `https://github.com/intermine/intermine/issues/1451`

The copy of a list by an un-logged user, saves the new list into db with the same name

---

bio/postprocess/main/src/org/intermine/bio/postprocess/PopulateChildFeatures.java
bio/webapp/src/org/intermine/webservice/server/jbrowse/genomic/Engine.java

should be tested (postprocess and webapp) with flymine or humanmine.

corrects issues with subfeatures in jbrowse

---

intermine/api/main/src/org/intermine/api/query/PathQueryExecutor.java
intermine/api/main/src/org/intermine/api/query/WebResultsExecutor.java

Read the last comment on the ticket #1469 to test the fix

1469 list internal error

---

RELEASE_NOTES
intermine/api/main/src/org/intermine/api/query/QueryExecutor.java
intermine/web/main/src/org/intermine/web/logic/Constants.java
intermine/web/main/src/org/intermine/webservice/server/query/result/QueryResultService.java
intermine/web/main/src/org/intermine/webservice/server/query/result/TableRowService.java
intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties

#1482 - Error when creating a list and accessing via the web service via tablerows method.

InterMine 1.7.1

---

bio/webapp/src/org/intermine/bio/web/widget/GeneLengthCorrectionCoefficient.java
intermine/web/main/src/org/intermine/web/logic/widget/EnrichmentWidget.java
intermine/web/test/src/org/intermine/web/logic/widget/EnrichmentWidgetTest.java

Gene length coefficient fix

---

RELEASE_NOTES
flymine/webapp/resources/webapp/WEB-INF/webconfig-model.xml
intermine/api/main/src/org/intermine/api/profile/Profile.java
intermine/web/main/src/org/intermine/web/struts/oauth2/Callback.java
intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties

See #1533 
Same pull request as #1541 but this is going into master instead of dev.

InterMine 1.7.2 - Google Fix

---

bio/sources/chado-db/main/src/org/intermine/bio/dataconversion/FlyBaseProcessor.java
intermine/web/main/src/org/intermine/webservice/server/search/QuickSearch.java

add search result count to output. Refs #964 
Let me know if you want me to change the name.

add search result count to output. Refs #964

---

intermine/api/main/src/org/intermine/api/profile/ProfileManager.java

Fixed savedQuery error. Refs. #1458

---

intermine/objectstore/main/src/org/intermine/sql/Database.java

really small change, and did a small build to test. fine to merge immediately i think.

adds filter for db property 'encoding' #739

---

intermine/api/main/src/org/intermine/api/query/MainHelper.java

minor teak to enable DOES_NOT_CONTAIN in query xml

support for DOES_NOT_CONTAIN in query xml

---

intermine/webapp/main/resources/webapp/css/bag.css

make list operations unclickable until user selects a list. Refs #288

make list operations unclickable until user selects a list. Refs #288

---

intermine/webapp/main/resources/webapp/WEB-INF/global.web.properties

How to test:
1. Clone branch.
2. Open global.web.properties
3. On line 63 change http://cdn to http://cdn-dev
4. Continue with https://github.com/intermine/intermine/issues/1328

Always use latest patch release of im-tables. Fixes issue #1328

---

flymine/webapp/resources/web.properties
intermine/objectstore/main/src/org/intermine/sql/Database.java
intermine/web/main/src/org/intermine/webservice/server/ServicesListingsServlet.java

adds and tests the possibility of adding default queries to iodocs. hopefully solves checkstyle error in previous pull attempt.

789 ws query defaults

---

intermine/web/main/src/org/intermine/webservice/server/lists/ListMakerService.java
intermine/web/main/src/org/intermine/webservice/server/lists/ListOperationService.java

Web service: list union - resulting type is NULL

---

intermine/web/main/src/org/intermine/web/logic/pathqueryresult/PathQueryResultHelper.java
intermine/web/test/src/org/intermine/web/logic/pathqueryresult/PathQueryResultsHelperTest.java

removed the ban on subtype (#1296). seems fine to me, but please test

removes subtype ban #1296

---

bio/webapp/src/org/intermine/bio/web/logic/GenomicRegionSearchService.java

Skip blank lines when you upload files to the region search.
Test and make sure this doesn't skip good lines! It looks okay to me.
Refs #802

skip blank lines in region search upload Refs #802

---

intermine/api/main/src/org/intermine/api/bag/BagManager.java
intermine/web/main/src/org/intermine/web/struts/ListTagsController.java
intermine/webapp/main/resources/webapp/WEB-INF/struts-config.xml
intermine/webapp/main/resources/webapp/WEB-INF/tiles-defs.xml
intermine/webapp/main/resources/webapp/bagView.jsp
intermine/webapp/main/resources/webapp/js/imdwr.js
intermine/webapp/main/resources/webapp/listTags.jsp
intermine/webapp/main/resources/webapp/templates.jsp
intermine/webapp/main/resources/webapp/webSearchableList.jsp
intermine/webapp/main/resources/webapp/wsBagLine.jsp
intermine/webapp/main/resources/webapp/wsBagRow.jsp
intermine/webapp/main/resources/webapp/wsBagTable.jsp
intermine/webapp/main/resources/webapp/wsFilterList.jsp

Refs #702
Add a show tags checkbox to lists page. 
@JoeCarlson Can you test this to make sure this is useful to you / what you asked for?

Add "Show Tags" option to Lists page #702

---

intermine/web/main/src/org/intermine/web/struts/SummariseTemplatesAction.java
intermine/webapp/main/resources/webapp/WEB-INF/classes/InterMineWebApp.properties
intermine/webapp/main/resources/webapp/historyTemplateView.jsp

Added a summarise all link to the bottom of the templates page. 
Refs #1382

add summarise all link to bottom of templates page. Refs #1382

---

intermine/web/main/src/org/intermine/web/logic/bag/WebJobInput.java
intermine/web/main/src/org/intermine/web/struts/BuildBagForm.java
intermine/web/main/src/org/intermine/web/struts/PortalQueryAction.java
intermine/webapp/main/resources/webapp/WEB-INF/struts-config.xml

forward to list upload if flag is set. Refs #1606

---

bio/core/main/src/org/intermine/bio/ontology/OboParser.java

allow ontology terms to not have a name. Refs #1613

---

intermine/api/main/src/org/intermine/api/InterMineAPI.java
intermine/api/main/src/org/intermine/api/profile/Profile.java
intermine/api/main/src/org/intermine/api/profile/ProfileManager.java
intermine/api/main/src/org/intermine/api/profile/TagManager.java
intermine/api/main/src/org/intermine/api/query/MainHelper.java
intermine/api/main/src/org/intermine/api/query/PathQueryAPI.java
intermine/api/main/src/org/intermine/api/template/TemplateManager.java
intermine/api/test/src/org/intermine/api/tracker/TrackerDelegateTest.java
intermine/web/main/src/org/intermine/web/struts/ImportTagsAction.java
intermine/web/main/src/org/intermine/web/struts/SummariseTemplatesAction.java
intermine/web/main/src/org/intermine/web/struts/TemplateAction.java
intermine/web/main/src/org/intermine/web/struts/TemplatesImportAction.java
intermine/web/test/src/org/intermine/web/struts/TestInterMineAPI.java
intermine/webtasks/main/src/org/intermine/web/commandline/PerformanceTester.java
intermine/webtasks/main/src/org/intermine/web/task/PrecomputeTemplatesTask.java

cache the list of valid global templates

---

intermine/web/main/src/org/intermine/web/logic/Constants.java
intermine/web/main/src/org/intermine/webservice/server/user/WhoAmIService.java

add user id to web service. Refs #1652

---

intermine/web/main/src/org/intermine/webservice/server/user/WhoAmIService.java

Fixed /user/whoami service failing for anonymous users

---

testmodel/build.gradle

Added ingored test failures in testmodel webapp

---

intermine/api/build.gradle
intermine/integrate/build.gradle
intermine/model/build.gradle
intermine/objectstore/build.gradle
intermine/objectstore/src/main/java/org/intermine/task/BuildDbTask.java
intermine/objectstore/src/main/java/org/intermine/task/StoreMetadataTask.java
intermine/pathquery/build.gradle
intermine/testresources/build.gradle
intermine/webapp/build.gradle

Yellow mellow

---

bio/build.gradle

keep running the bio tests even if we encounter a failure for now

---

.travis.yml
config/ci-bio.properties
config/init-webapp.sh
config/travis/init.sh
config/travis/run.sh
plugin/build.gradle

reactivate bio test suite, though chances are it doesn't work at travis.org yet

---

intermine/web/main/src/org/intermine/web/logic/help/HintManager.java
intermine/web/main/src/org/intermine/web/struts/HintsController.java
intermine/web/test/resources/HintManagerTest.properties
intermine/web/test/src/org/intermine/web/logic/help/HintManagerTest.java
intermine/webapp/main/resources/webapp/WEB-INF/struts-config.xml
intermine/webapp/main/resources/webapp/WEB-INF/tiles-defs.xml
intermine/webapp/main/resources/webapp/hints.jsp
intermine/webapp/main/resources/webapp/layout.jsp

Reverts intermine/intermine#1687

Revert "Remove hint manager"

---

intermine/web/main/src/org/intermine/web/struts/InitialiserPlugin.java
intermine/web/main/src/org/intermine/web/struts/Registrar.java

Reverts intermine/intermine#1688

Revert "Delete old registry"

---

bio/postprocess/main/src/org/intermine/bio/postprocess/CreateLocationOverlapIndex.java
bio/postprocess/main/src/org/intermine/bio/postprocess/OverlapViewTask.java
bio/postprocess/main/src/org/intermine/bio/postprocess/PostProcessOperationsTask.java
humanmine/project.xml
intermine/objectstore/main/src/org/intermine/objectstore/intermine/DatabaseSchema.java
intermine/objectstore/main/src/org/intermine/objectstore/intermine/ObjectStoreInterMineImpl.java
intermine/objectstore/main/src/org/intermine/objectstore/intermine/SqlGenerator.java
intermine/objectstore/main/src/org/intermine/objectstore/intermine/TorqueModelOutputTask.java
intermine/objectstore/test/src/org/intermine/objectstore/intermine/DatabaseSchemaTest.java
intermine/objectstore/test/src/org/intermine/objectstore/intermine/SqlGeneratorTest.java
intermine/objectstore/test/src/org/intermine/objectstore/intermine/WithNotXmlSqlGeneratorTest.java

Remove all references to bioseg in the code. This is adding complexity, and for InterMine 2.0 we are going to require Postgres 9.3.x anyway so we don't need anymore. 
Refs #1109  
Make sure the region search behaves correctly.

Killing bioseg

---

bio/core/main/src/org/intermine/bio/ontology/OboParser.java

Putting alt_ids in obo files in the cross references collection.
Refs #412
Does this solve our problem? 

add alt ids as xrefs. 

---

bio/postprocess/main/src/org/intermine/bio/postprocess/IntronUtil.java

This post-processor is fine, but it stores FlyMine-specific text in the DataSource and DataSet. I've made it generic.

Remove FlyMine-specific verbiage

---

intermine/objectstore/build.gradle

For InterMine 2.0 we are increasing our software requirements to Java 8 and Postgres 9.3x. We should use the modern drivers.
Refs #1812 
* database builds
* data is correct
* webapp runs queries as expected.
- [ x ] Passing unit test for new or updated code (if applicable)
- [ x ] Passes all tests – according to Travis
- [ x ] Single purpose
- [ x ] Detailed commit messages

update postgres and hikari versions

---

bio/core/main/src/org/intermine/bio/ontology/OboParser.java

I think I've got this in an up-to-date dev branch now. Allows null name field in the OBO.

---

bio/webapp/src/org/intermine/bio/web/export/SequenceExporter.java

Would you believe, attempt #4???
@sergiocontrino and @julie-sullivan , all that discussion was really useful (to me, anyway) and resulted in this pull request, which is much simpler than the previous one(s).

Update to avoid reading whole chromosomes.

---

bio/sources/example-sources/kegg-example/build.gradle
bio/sources/example-sources/kegg-identifiers/build.gradle
bio/sources/example-sources/malaria-gff/build.gradle

updated bio example sources so they can be installed locally

---

README.md
RELEASE_NOTES
bio/build.gradle
bio/postprocess/build.gradle
bio/sources/build.gradle
intermine/build.gradle
intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
plugin/build.gradle

Forgot to update the version numbers.

InterMine 2.1.1 (update version numbers)

---

config/run-ws-tests.sh

Travis sets up imjs from scratch. It looks like one of the very aged dependencies is being flaky. [Bower is deprecated](https://www.npmjs.com/package/bower) and fails to install its dependencies properly as part of the imjs setup script. It still installs everything just fine when installed outside the script for some reason, so I've simply added a couple of lines to this effect. 
I'm pretty sure this is a band-aid over the fact that imjs needs serious maintenance / dependency updates, but it will (I hope) fix it for now. In the medium term I think we'll be forced to give imjs and imtables some tlc. 
This is fixing the setup for a test suite - so if travis passes, you know the fix worked ;) 

attempting to fix failure installing the webservice tests

---

bio/build.gradle
bio/postprocess/build.gradle
bio/sources/build.gradle
bio/sources/settings.gradle
intermine/build.gradle
plugin/build.gradle

I have already tested it in order to upload bio-source-malaria-gff.

Changed bintray configuration to be able to upload artifact to bintray under org/intermine

---

intermine/api/src/main/java/org/intermine/api/query/MainHelper.java

Refs #1847
Make sure DOES NOT CONTAIN op acts as expected

add does not contain op. 

---

bio/webapp/build.gradle
intermine/webapp/build.gradle
testmine/webapp/build.gradle

The gretty.plugin URL in three build.gradle files suddenly broke today at GitHub. I've replaced it with a working version.

Updated gretty.plugin URL

---

intermine/api/src/main/java/org/intermine/api/searchengine/solr/SolrIndexHandler.java
intermine/api/src/main/java/org/intermine/api/searchengine/solr/SolrObjectHandler.java
intermine/webapp/src/main/java/org/intermine/web/autocompletion/AutoCompleter.java

I have added multiple conditions to check whether same Field names are added to Solr ManagedSchema again and again. 
Basically following three updates are validated : 
- FieldTypeDefinitions
- Fields
- CopyFields
Resolves #1970 
Tested with Solr 7.2.1 and Solr 7.6.0

modify SolrIndexHandler to support newer Solr versions

---

bio/webapp/src/main/webapp/model/proteinAtlasDisplayer.jsp

Fix for #1988 - need advice on whether "staining" is still appropriate wording before we can merge.
@rachellyne - this viewer used to look at a variable which had EITHER the value "ape" or the value "staining" and would set ape to blue, or staining to red. that variable was removed from the data so I'm not sure what to replace the word staining with: 
visit the report page for a gene and look for a view near the top like the screenshot above.

remove the failing bits from the jsp template

---

bio/sources/go-annotation/src/main/java/org/intermine/bio/dataconversion/GoConverter.java
bio/sources/go-annotation/src/test/java/org/intermine/bio/dataconversion/GoConverterTest.java
bio/sources/go-annotation/src/test/resources/GoConverterOboTest_tgt.xml

update the dataset to be where the data file came from. Refs #1941

---

bio/core/build.gradle
bio/model/build.gradle

After removing the file intermine-bio-test.properties from .intermine directory, verify you are still able to install bio modules successfully
intermine/bio$./gradlew clean install

Fix issue #1773

---

intermine/objectstore/src/main/java/org/intermine/objectstore/ObjectStoreSummary.java

ObjectStoreSummary does not ignore fields consistently. At one point, the code ignores fields based on their full qualified name, and at a later point, using an unqualified name. #2036

Correct (typo?) in ignoreField test

---

intermine/webapp/src/main/java/org/intermine/web/fair/SemanticMarkupUtil.java

updated the code to read the web.properties file

---

README.md
RELEASE_NOTES
bio/build.gradle
bio/model/core.xml
bio/postprocess/build.gradle
bio/sources/build.gradle
intermine/build.gradle
intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
plugin/build.gradle

Refs #2060
Strains were in 3.1.2 but not 4.0.0. I don't know why. When I do a `git diff`I get no results. 
I manually updated the files.

InterMine 4.0.1 - restore strains

---

README.md
RELEASE_NOTES
bio/build.gradle
bio/model/core.xml
bio/postprocess/build.gradle
bio/sources/build.gradle
intermine/build.gradle
intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
plugin/build.gradle

#2060 - Restore Strains to core data model

InterMine 4.0.1

---

bio/model/core.xml

The strains got lost, so I restored. Need to re-add the annotations added in 4.0

merge back the 4.0 annotations back in

---

bio/gradle/wrapper/gradle-wrapper.properties
bio/postprocess/gradle/wrapper/gradle-wrapper.properties
bio/sources/gradle/wrapper/gradle-wrapper.properties
intermine/gradle/wrapper/gradle-wrapper.properties
plugin/gradle/wrapper/gradle-wrapper.properties
plugin/src/main/groovy/org/intermine/plugin/dbmodel/BioSourceDBModelPlugin.groovy

Update to gradle 4.9

---

bio/build.gradle
bio/gradle.properties
bio/postprocess-test/build.gradle
bio/postprocess-test/gradle.properties
bio/postprocess/build.gradle
bio/postprocess/gradle.properties
bio/sources/build.gradle
bio/sources/gradle.properties
intermine/build.gradle
intermine/gradle.properties
plugin/build.gradle
plugin/gradle.properties
testmine/build.gradle

updated im version to 4.1.0

---

README.md

InterMine 4.1.0

---

plugin/src/main/groovy/org/intermine/plugin/dbmodel/DBModelPlugin.groovy
plugin/src/main/groovy/org/intermine/plugin/dbmodel/DBModelUtils.groovy
plugin/src/main/groovy/org/intermine/plugin/integrate/IntegratePlugin.groovy

I have tested with biotestmine but it would be better to test with flymine too.
We need first update the gradle wrapper in flymine and then rebuild the db + postprocesses + deploy webapp.
to update the gradle wrapper
`cd flymine/ && ./gradlew wrapper --gradle-version=4.9 `
My changes involve only the intemine plugin

Build a mine (db + deploy webapp) using gradle 4.9

---

CODE-OF-CONDUCT.md
CONTRIBUTING.md

adds mention of code of conduct to the contributing file.

add code of conduct to contributing file

---

bio/core/src/main/resources/entrezIdResolver_config.properties

ThaleMine ID Resolver configuration.
This is based on old Araport ThaleMine. Without this ID resolver, some of Intermine's loaders are not working.

BAR ThaleMine - 1

---

intermine/api/src/main/java/org/intermine/api/query/codegen/WebservicePythonCodeGenerator.java
intermine/api/src/test/resources/org/intermine/api/query/codegen/noneof-template.python.expected
intermine/api/src/test/resources/org/intermine/api/query/codegen/oneof-template.python.expected

This pull request fixes a bug in the generated python code, where lists have quotes around them, but they shouldn't.
Thoughts? Comments?
Tests in Python 2.7.16, 3.6.9 and 3.7.4

Fixed intermine #1981

---

intermine/api/src/main/java/org/intermine/api/bag/BagManager.java

see #2129 . just review the code.I have redeployed the webapp with success

Ticket2129

---

bio/sources/biogrid/src/main/resources/biogrid_config.properties

This is our contribution to BioGrid data source. 
It is working on the BAR ThaleMine dev and live versions.

ThaleMine Updates to BioGrid

---

bio/sources/psi/src/main/java/org/intermine/bio/dataconversion/PsiConverter.java
bio/sources/psi/src/main/resources/psi-intact_config.properties

This pull request updates psi BioSource to include ThaleMine support. Please review the changes. Note: These changes are very similar the Araport ThaleMine psi source.
The changes are tested using the current live and dev versions of ThaleMine at the Bio-Analytic Resource.

ThaleMine Updates to psi BioSource

---

bio/postprocess/create-autocomplete-index/src/main/java/org/intermine/bio/postprocess/CreateAutocompleteIndexProcess.java
bio/postprocess/create-search-index/src/main/java/org/intermine/bio/postprocess/CreateSearchIndexProcess.java
intermine/api/src/main/java/org/intermine/api/searchengine/IndexHandler.java
intermine/api/src/main/java/org/intermine/api/searchengine/solr/SolrIndexHandler.java
intermine/integrate/src/main/java/org/intermine/postprocess/PostProcessor.java
intermine/webapp/src/main/java/org/intermine/web/autocompletion/AutoCompleter.java
plugin/src/main/groovy/org/intermine/plugin/postprocess/PostProcessPlugin.groovy

Re-install plugin, intermine, bio and bio-postprocess.
Execute
` 
./gradlew postprocess -Pprocess=create-search-index
./gradlew postprocess -Pprocess=create-autocomplete-index
`
and verify that work fine.
Stop solr and execute again (a nice message should be displayed)

Ticket2120 (solr failure message)

---

plugin/src/main/groovy/org/intermine/plugin/postprocess/PostProcessPlugin.groovy

IMproved the message displayed to the user. #2120

---

bio/sources/gff/build.gradle
bio/sources/settings.gradle

I have tested with biotestmine, replacing malaria-gff type with gff type. The build works and the webapp display the gene loaded by the gene gene.46311 loaded from MAL1.gff3 file

Added default gff bio-source. see #2164

---

intermine/webapp/src/main/java/org/intermine/web/logic/results/ReportObjectField.java
intermine/webapp/src/main/webapp/report.jsp

fix broken report page for protein see #2161

---

intermine/api/src/main/java/org/intermine/api/uri/ClassNameURIIdentifierMapper.java
intermine/api/src/main/resources/uri_keys.properties

Remove from the mine/dbmodel/resources/class_keys.properties file all the properties with key ending with _URI related to the classes in the core model (no Complex e.g), redeploy the webapp and check in the report page that the share link for gene uses primaryIdentifier, protein uses primaryAccesion, publication uses pubMedId

Improve config 2178

---

intermine/webapp/src/main/java/org/intermine/web/struts/HtmlHeadController.java

This pull request fixes a bug in InterMine. This bug was discovered by TACC (Texas Advanced Computing Center) security staff and reported by Erik Ferlanti.
The bug is in reports page. To test, add the following to the end of any InterMine URL (Example: bar.utoronto.ca/thalemine/):
report.do?id=108386942</title><img%20src=x%20onerror=alert(150)>&trail=%7C108386942
Please test it and let me know if you have any questions.

Minor bug fix

---

intermine/webapp/src/main/webapp/WEB-INF/global.web.properties

Loop query (updated im.js)

---

bio/webapp/src/main/java/org/intermine/webservice/server/complexes/ExportService.java

No need to test. It works on humanmine locally. Please just review and merge it. thk

fixed Complex viewer. see #2145

---

README.md
RELEASE_NOTES
bio/build.gradle
bio/postprocess-test/build.gradle
bio/postprocess/build.gradle
bio/sources/build.gradle
intermine/build.gradle
intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
plugin/build.gradle

Prepare release

---

intermine/webapp/src/main/webapp/WEB-INF/global.web.properties

Updated im-tables version to fix #2045 and #2107

---

intermine/api/src/main/java/org/intermine/api/template/ApiTemplate.java
intermine/webapp/src/main/java/org/intermine/web/fair/SemanticMarkupFormatter.java
intermine/webapp/src/main/java/org/intermine/web/struts/BeginAction.java
intermine/webapp/src/main/java/org/intermine/webservice/server/fair/HomePageMarkupService.java

This PR should fix ticket #2203 and ticket #2208 

Public template and delete template

---

bio/sources/vcf/src/main/java/org/intermine/bio/dataconversion/VcfLoaderTask.java

I have tested using a couple of files download from ftp://ftp.ensembl.org/pub/release-79/variation/vcf/homo_sapiens/
To configure a vcf source doc [here](https://intermine.readthedocs.io/en/latest/database/data-sources/library/variation/vcf/)

vcf fixed. see #2204

---

intermine/webapp/src/main/java/org/intermine/webservice/server/webproperties/WebPropertiesService.java
intermine/webapp/src/main/webapp/WEB-INF/global.web.properties

test link to humanmine from flymine report page (e.g. gene  MYH16)

Links to other mines

---

intermine/webapp/src/main/java/org/intermine/webservice/server/webproperties/WebPropertiesService.java

This solve service/web-properties 500 error issue

Fixed web-properties issue by code and not removing properties. see #2190

---

intermine/webapp/src/main/java/org/intermine/web/fair/SemanticMarkupFormatter.java
intermine/webapp/src/main/java/org/intermine/web/filters/PermanentURLFilter.java
intermine/webapp/src/main/java/org/intermine/web/logic/PermanentURIHelper.java
intermine/webapp/src/main/java/org/intermine/web/struts/ReportController.java
intermine/webapp/src/main/java/org/intermine/web/uri/ClassNameURIIdentifierMapper.java
intermine/webapp/src/main/java/org/intermine/web/uri/InterMineLUI.java
intermine/webapp/src/main/java/org/intermine/web/uri/InterMineLUIConverter.java
intermine/webapp/src/main/java/org/intermine/web/uri/InvalidPermanentURLException.java
intermine/webapp/src/main/java/org/intermine/webservice/server/fair/BioEntityMarkupService.java
intermine/webapp/src/main/java/org/intermine/webservice/server/fair/PermanentURLService.java
intermine/webapp/src/test/java/org/intermine/web/uri/ClassNameURIIdentifierMapperTest.java
intermine/webapp/src/test/java/org/intermine/web/uri/InterMineLUIConverterTest.java
intermine/webapp/src/test/java/org/intermine/web/uri/InterMineLUITest.java
intermine/webapp/src/test/java/org/intermine/web/uri/MockInterMineLUIConverter.java

Public template issue fixed completely

Ticket 2203

---

intermine/api/src/main/java/org/intermine/api/query/MainHelper.java

Fix issue on date filtering #2237

---

intermine/api/src/main/java/org/intermine/api/template/TemplateHelper.java

Fixed optional contraint not returned by ws. see #2242

---

intermine/webapp/src/main/java/org/intermine/web/fair/SemanticMarkupFormatter.java
intermine/webapp/src/main/java/org/intermine/web/logic/results/ReportObject.java

Improved DataRecord

---

bio/sources/go-annotation/src/main/resources/go-annotation_config.properties

This pull request makes go-annotation loader work on ThaleMine.
We have tested it on ThaleMine dev and live versions.

BAR ThaleMine - 7: go-annotation loader

---

intermine/webapp/src/main/java/org/intermine/webservice/server/user/LoginService.java
plugin/src/main/groovy/org/intermine/plugin/integrate/IntegrateUtils.groovy

removed mergedTemplates because unneccessary

---

bio/sources/fasta/src/main/java/org/intermine/bio/dataconversion/UniProtFastaLoaderTask.java

FIxed UniprotFastaLoaderTask see #2259

---

README.md
bio/build.gradle
bio/gradle.properties
bio/postprocess-test/build.gradle
bio/postprocess-test/gradle.properties
bio/postprocess/build.gradle
bio/postprocess/gradle.properties
bio/sources/build.gradle
bio/sources/gradle.properties
intermine/build.gradle
intermine/gradle.properties
intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
intermine/webapp/src/main/webapp/WEB-INF/global.web.properties
plugin/build.gradle
plugin/gradle.properties
testmine/build.gradle

Preparing release + list widgets

---

bio/sources/fasta/src/main/java/org/intermine/bio/dataconversion/UniProtFastaLoaderTask.java

FIxed UniprotFastaLoaderTaskTest see #2259

---

.travis.yml
bio/build.gradle
bio/postprocess-test/build.gradle
bio/postprocess-test/gradle/wrapper/gradle-wrapper.properties
bio/postprocess/build.gradle
bio/sources/build.gradle
config/travis/init-solr.sh
config/travis/init.sh
config/travis/run.sh
intermine/build.gradle
intermine/objectstore/src/test/java/org/intermine/objectstore/intermine/ObjectStoreInterMineImplTestCase.java

I was trying to update Python module to Python 3+ and discovered that InterMine build system needs to update to a more modern Travis Ubuntu. Here is an update. This is one step towards #2271 
This updated the following
- Ubuntu 18.04 (20.04 doesn't have Python 2.7)
- OpenJDK 11
- PostgreSQL 11
- Solr 8.6.2  (Current Solr doesn't work with old Java)
Testing Travis CI ...

Travis Update

---

intermine/webapp/src/main/webapp/WEB-INF/global.web.properties

Deployed on alpha and tested there wiht an existing account and with a new one

fixed google oauth2 endpoints. see #2296

---

bio/postprocess/create-R2RML-mapping/src/main/java/org/intermine/bio/postprocess/R2RMLMappingProcess.java

Add SIB Swiss Institute as Co copyright holder and add a bit of JavaDoc

---

testmine/setup.sh
testmine/webapp/build.gradle

2 old commit related to remove gretty from testmine

---

intermine/webapp/src/main/java/org/intermine/web/uri/InterMineLUIConverter.java

see ticket https://github.com/intermine/intermine/issues/2279
To test just set in the class_keys.properties file of the mine the following value
`Publication_URI = title`
Then redeploy the webapp and verify that the report page of a publication entity with no title, still works and doesn't display the Share button

Npe report page

---

README.md
RELEASE_NOTES
bio/build.gradle
bio/gradle.properties
bio/postprocess-test/build.gradle
bio/postprocess-test/gradle.properties
bio/postprocess/build.gradle
bio/postprocess/gradle.properties
bio/sources/build.gradle
bio/sources/gradle.properties
intermine/build.gradle
intermine/gradle.properties
intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
plugin/build.gradle
plugin/gradle.properties
testmine/build.gradle

Release 4.3.0

---

intermine/webapp/src/main/java/org/intermine/webservice/server/idresolution/ListResolutionService.java
intermine/webapp/src/main/java/org/intermine/webservice/server/idresolution/ListResolutionServlet.java
intermine/webapp/src/main/java/org/intermine/webservice/server/lists/ListUpgradingService.java
intermine/webapp/src/main/java/org/intermine/webservice/server/lists/ListUpgradingServlet.java
intermine/webapp/src/main/webapp/WEB-INF/web.xml

WS for upgrading lists

---

intermine/webapp/src/main/java/org/intermine/webservice/server/query/result/FrictionlessDataPackage.java

Fixed datasources url when there are source with similar names

---

intermine/api/src/main/java/org/intermine/api/profile/TagManager.java
intermine/api/src/main/java/org/intermine/api/tag/TagNames.java

Fix tags returned by service/lists

---

bio/build.gradle
bio/core/build.gradle
bio/gradle.properties
bio/model/build.gradle
bio/postprocess-test/build.gradle
bio/postprocess-test/gradle.properties
bio/postprocess/build.gradle
bio/postprocess/gradle.properties
bio/sources/build.gradle
bio/sources/fasta/build.gradle
bio/sources/gradle.properties
intermine/build.gradle
intermine/gradle.properties
plugin/build.gradle
plugin/gradle.properties
testmine/build.gradle
testmine/webapp/build.gradle

Replace Jcenter

---

README.md
RELEASE_NOTES
bio/build.gradle
bio/gradle.properties
bio/postprocess-test/gradle.properties
bio/postprocess/build.gradle
bio/postprocess/gradle.properties
bio/sources/build.gradle
bio/sources/gradle.properties
bio/webapp/build.gradle
intermine/build.gradle
intermine/gradle.properties
plugin/build.gradle
plugin/gradle.properties

Merge dev into bluegene branch

---

intermine/webapp/src/main/java/org/intermine/webservice/server/widget/EnrichmentWidgetResultService.java

fixed enrichement widget failing with population + ids. see #2352

---

intermine/webapp/src/main/java/org/intermine/web/logic/widget/GraphWidget.java
intermine/webapp/src/main/java/org/intermine/web/logic/widget/GraphWidgetLoader.java
intermine/webapp/src/main/java/org/intermine/web/logic/widget/TableWidget.java
intermine/webapp/src/main/java/org/intermine/web/logic/widget/TableWidgetLdr.java
intermine/webapp/src/main/java/org/intermine/web/logic/widget/WidgetLdr.java
intermine/webapp/src/main/java/org/intermine/web/logic/widget/config/GraphWidgetConfig.java
intermine/webapp/src/main/java/org/intermine/webservice/server/widget/GraphService.java
intermine/webapp/src/main/java/org/intermine/webservice/server/widget/WidgetsRequestParser.java
intermine/webapp/src/main/java/org/intermine/webservice/server/widget/WidgetsServiceInput.java
intermine/webapp/src/main/webapp/WEB-INF/web.xml

Fix graph and table widgtes

---

intermine/webapp/src/main/java/org/intermine/web/struts/BuildBagAction.java

check the bag type in the upload form see #2358

---

intermine/webapp/src/main/java/org/intermine/web/struts/BuildBagAction.java

use intermineapi instead  #2358

---

intermine/webapp/src/main/java/org/intermine/web/struts/BuildBagAction.java

fixed checkstyle  #2358

---

intermine/webapp/src/main/java/org/intermine/web/struts/BuildBagAction.java

moved check after empty check  #2358

---

intermine/webapp/src/main/java/org/intermine/webservice/server/widget/GraphService.java
intermine/webapp/src/main/java/org/intermine/webservice/server/widget/TableWidgetService.java

add the type in the response

---

README.md
RELEASE_NOTES
bio/build.gradle
bio/postprocess-test/build.gradle
bio/postprocess/build.gradle
bio/sources/build.gradle
intermine/build.gradle
intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
plugin/build.gradle

release 5.0.1

---

README.md
RELEASE_NOTES
bio/build.gradle
bio/gradle.properties
bio/postprocess-test/build.gradle
bio/postprocess-test/gradle.properties
bio/postprocess/build.gradle
bio/postprocess/gradle.properties
bio/sources/build.gradle
bio/sources/gradle.properties
intermine/build.gradle
intermine/gradle.properties
intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
plugin/build.gradle
plugin/gradle.properties
testmine/build.gradle

release 5.0.2

---

README.md
RELEASE_NOTES
bio/build.gradle
bio/gradle.properties
bio/postprocess-test/build.gradle
bio/postprocess-test/gradle.properties
bio/postprocess/build.gradle
bio/postprocess/gradle.properties
bio/sources/build.gradle
bio/sources/gradle.properties
intermine/build.gradle
intermine/gradle.properties
intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
intermine/webapp/src/main/java/org/intermine/webservice/server/widget/EnrichmentWidgetResultService.java
plugin/build.gradle
plugin/gradle.properties
testmine/build.gradle

Intermine 5.0.3

---

bio/sources/biogrid/src/main/resources/biogrid_config.properties

Updated biogrid configuration for pombe

---

README.md
RELEASE_NOTES
bio/build.gradle
bio/gradle.properties
bio/postprocess-test/build.gradle
bio/postprocess-test/gradle.properties
bio/postprocess/build.gradle
bio/postprocess/gradle.properties
bio/sources/build.gradle
bio/sources/gradle.properties
intermine/build.gradle
intermine/gradle.properties
intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
plugin/build.gradle
plugin/gradle.properties
testmine/build.gradle

release 5.0.4

---

bio/sources/build.gradle
intermine/build.gradle
testmine/build.gradle

If this work, please merge this. We will figure out Log4j 1 to Log4j2 transition later.
Testing using BioTestMine needed.

Log4j-1x compatibility upgrade.

---

README.md
RELEASE_NOTES
bio/build.gradle
bio/gradle.properties
bio/postprocess-test/build.gradle
bio/postprocess-test/gradle.properties
bio/postprocess/build.gradle
bio/postprocess/gradle.properties
bio/sources/build.gradle
bio/sources/gradle.properties
intermine/build.gradle
intermine/gradle.properties
intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
plugin/build.gradle
plugin/gradle.properties
testmine/build.gradle

release 5.0.5

---

bio/webapp/build.gradle

This should remove:
./WEB-INF/lib/log4j-1.2.16.jar
Looks ok on ThaleMine v5.0.5-20210109

Log4j fix round 2

---

README.md
RELEASE_NOTES
bio/build.gradle
bio/gradle.properties
bio/postprocess-test/build.gradle
bio/postprocess-test/gradle.properties
bio/postprocess/build.gradle
bio/postprocess/gradle.properties
bio/sources/build.gradle
bio/sources/gradle.properties
intermine/build.gradle
intermine/gradle.properties
intermine/webapp/src/main/java/org/intermine/web/logic/Constants.java
plugin/build.gradle
plugin/gradle.properties
testmine/build.gradle

release 5.0.6

---

bio/core/src/main/resources/entrezIdResolver_config.properties

Added pombe organims to the taxon id to be ignored by the idresolver

---

bio/core/build.gradle
bio/gradle.properties
bio/postprocess-test/build.gradle
bio/postprocess-test/gradle.properties
bio/sources/fasta/build.gradle
bio/sources/gradle.properties

Removed jcenter dependecies

---

intermine/webapp/src/main/java/org/intermine/web/struts/SubMenuController.java

fixed XSS issue #2425

---

bio/model/core.xml

Remove SyntenyBlock.publications collection since it is redundant with dataSets, which have a publication reference.
Not much to test here, I don't think there is a synteny loader in core IM.

Remove publications collection - redundant with dataSets.

---

bio/model/core.xml

Reverts intermine/intermine#2426

Revert "Remove publications collection - redundant with dataSets."

---

intermine/webapp/src/main/java/org/intermine/web/logic/results/ReportObject.java
intermine/webapp/src/main/java/org/intermine/web/struts/BeginAction.java
intermine/webapp/src/main/java/org/intermine/web/struts/HtmlHeadController.java

Prevent np exception

---

RELEASE_NOTES

preparing release 5.1.0
